title: Brook's Blog
email: brook.a.abraha@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog on topics I find interesting in computer science, mathematics and software engineering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: primebrook
linkedin_username: brook-abraha-652168203
# google_analytics: YOUR-TRACKING-ID  # Add your Google Analytics ID if you have one
show_excerpts: true
# disqus:
#   shortname: your-disqus-shortname  # Add your Disqus shortname if you want comments

permalink: /:title:output_ext

header_pages:
  - about.html

markdown: kramdown
kramdown:
  parse_block_html: true
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
